[package]
name = "greedy_mesher"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = ["dynamic_linking", "bevy_gizmos", "bevy_pbr"] }
noise = "0.9.0"
rand = "0.9.0"
